# Generated by Django 4.2.7 on 2024-06-13 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='features',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.feature'),
        ),
    ]
