# Generated by Django 4.2.7 on 2024-06-13 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_feature_alter_project_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='features',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.feature'),
        ),
    ]
