# Generated by Django 4.2.7 on 2024-06-13 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_project_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='feature',
        ),
        migrations.AddField(
            model_name='feature',
            name='feature_add',
            field=models.CharField(default='Feature', max_length=80),
        ),
        migrations.AddField(
            model_name='feature',
            name='feature_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='features',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.feature'),
        ),
    ]
