# Generated by Django 4.2.7 on 2024-06-14 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='features',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.feature'),
        ),
        migrations.AlterField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
