# Generated by Django 4.2.7 on 2024-06-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_project_features_alter_project_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
