# Generated by Django 4.2.7 on 2024-06-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_add',
            field=models.CharField(max_length=80),
        ),
    ]
