# Generated by Django 4.2.7 on 2024-06-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_feature_feature_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='features',
        ),
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.ManyToManyField(blank=True, to='authentication.feature'),
        ),
    ]
