# Generated by Django 4.2.7 on 2024-06-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_project_features_project_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
