# Generated by Django 4.2.7 on 2024-06-20 05:53

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_project_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='token',
            field=authentication.models.TokenField(default='XXXX-XXXX-XXXX-XXXX', max_length=19),
        ),
    ]
