# Generated by Django 4.2.7 on 2024-06-20 06:08

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_project_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='token',
            field=authentication.models.TokenField(default='UKKS-MKLS-KPZX-COJD', max_length=19),
        ),
    ]
