# Generated by Django 4.2.7 on 2024-06-21 15:31

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_project_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='project',
            name='token',
            field=authentication.models.TokenField(default='DLTY-BGRP-NIIL-ESUL', max_length=19, unique=True),
        ),
    ]
