# Generated by Django 4.2.7 on 2024-06-21 15:52

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_project_name_alter_project_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='token',
            field=authentication.models.TokenField(max_length=19, unique=True),
        ),
    ]
