# Generated by Django 4.2.7 on 2024-06-29 22:03

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_project_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='token',
            field=authentication.models.TokenField(default='ZHZA-HLZW-SWHS-PTTY', max_length=20, unique=True),
        ),
    ]
