# Generated by Django 4.2.7 on 2024-07-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_alter_project_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='feature_notes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
