# Generated by Django 4.2.7 on 2024-07-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_feature_feature_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature_note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_note', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='feature',
            name='feature_notes',
        ),
        migrations.AddField(
            model_name='feature',
            name='feature_notes',
            field=models.ManyToManyField(blank=True, to='authentication.feature_note'),
        ),
    ]
